// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhicexfrpdymwdhxsgkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloaWNleGZycGR5bXdkaHhzZ2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTU3NTYsImV4cCI6MjA1ODQ3MTc1Nn0.qqjvnR8GO9yRdoqGDZmZ_gBEuIVr3abD6FGPAcxsVEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);